export default {
    collect: '/collect',
    collect_last: '/collect/last',
    collect_class: '/collect/class',
    progress: '/progress',
    videoclass: '/videoclass',
    classmap: '/classmap',
    video: '/video',
    video_online: '/video/online',
    video_page: '/video/page',
    videodl: '/video/dl',
    videocollect: '/video/collect',
    banner: '/banner',
    fixdl: '/fix/dl',
    view: '/video/view',
    viewcount: '/video/viewcount',

    Img_DOMIM: process.env.Img_DOMIM,
    API_DOMIN: process.env.API_DOMIN,
    Play_DOMIN: process.env.Play_DOMIN,
}